# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xB94NpopsOD9qIltZKvqM5eyFesey5N9
"""

#Task 1
raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma", "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ", "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA", "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ", "roll": "105", "marks_str": "75, 80, 70, 68, 85"}
]
cleaned_students = []

# Process raw_students to create cleaned_students
for student in raw_students:
    name = student["name"].strip().title() # Strip whitespace and title case:
    roll = int(student["roll"])  # Convert string to integer:

    # Split string and convert each string to integer:
    marks = list(map(int, student["marks_str"].split(",")))

    # Create the cleaned dictionary:
    cleaned_data = {
        "name": name,
        "roll": roll,
        "marks": marks
    }
    cleaned_students.append(cleaned_data)

# For each cleaned student, verify the name is valid: check that every word in the name contains only alphabetic characters. Print "✓ Valid name" or "✗ Invalid name" next to each student.
for student_data in cleaned_students:
    name = student_data["name"]
    words = name.split()
    is_valid_name = True
    for word in words:
        if not word.isalpha():
            is_valid_name = False
            break
    validation_text= "✓ Valid name" if is_valid_name else "✗ Invalid name"

    # Print a formatted profile card for each cleaned student using f-strings:
    print("================================")
    print(f"Student : {student_data['name']} ({validation_text})")
    print(f"Roll No: {student_data['roll']}")
    print(f"Marks: {student_data['marks']}")
    print("================================")
    print() #Space for next student

# After processing all students, print the name in ALL CAPS and lowercase for the student with roll number 103.
for student_data in cleaned_students:
    if student_data["roll"] == 103:
        print(f"Roll 103 Upper: {student_data['name'].upper()}")
        print(f"Roll 103 Lower: {student_data['name'].lower()}")
        break

#Task 2
student_name = "Ayesha Sharma"
subjects     = ["Math", "Physics", "CS", "English", "Chemistry"]
marks        = [88, 72, 95, 60, 78]
#Using a for loop to print each subject alongside its marks and a grade label.
for i in range(len(subjects)):
    score = marks[i]
    if score>=90:
      grade = "A+"
    elif score>=80:
      grade = "A"
    elif score>=70:
      grade = "B"
    elif score>=60:
      grade = "C"
    else:
      grade = "F"
    print(f"{subjects[i]}: {score} ({grade})")

#Calculate and print: Total marks (sum of all subjects)
                    # Average marks (rounded to 2 decimal places)
                    # Highest scoring subject (name + marks)
                    # Lowest scoring subject (name + marks)
total_marks = sum(marks)
avg_marks = round(total_marks/len(marks),2)
highest_score = max(marks)
lowest_score = min(marks)
print(f"\nTotal Marks: {total_marks}")
print(f"Average Marks: {avg_marks}")
print(f"Highest Scoring Subject: {subjects[marks.index(highest_score)]} ({highest_score})")
print(f"Lowest Scoring Subject: {subjects[marks.index(lowest_score)]} ({lowest_score})")


#While loop for marks-entry system
print("\n--- Marks Entry System (Type 'done' as subject name to stop)---")
new_subjects_count = 0
while True:
    sub_input = input("Enter subject name: ").strip()
    if sub_input.lower() == 'done':
        break
    mark_input = input(f"Enter marks for {sub_input}: ")
    if not mark_input.replace('.','',1).isdigit():
        print("Warning: Non-Numeric input detected. Please enter a numeric value between 0-100.")
        continue

    val = float(mark_input)
    if val < 0 or val > 100:
        print(f"Warning: {val} is outside the range 0-100. Entry ignored.")
        continue
    subjects.append(sub_input)
    marks.append(val)
    new_subjects_count += 1
updated_avg = round(sum(marks) / len(marks), 2)
print(f"\nNew subjects added: {new_subjects_count}")
print(f"Updated average across all {len(subjects)} subjects: {updated_avg}")

#Task 3
class_data = [
    ("Ayesha Sharma",  [88, 72, 95, 60, 78]),
    ("Rohit Verma",    [55, 68, 49, 72, 61]),
    ("Priya Nair",     [91, 85, 88, 94, 79]),
    ("Karan Mehta",    [40, 55, 38, 62, 50]),
    ("Sneha Pillai",   [75, 80, 70, 68, 85]),
]
#Variables to store summary data
pass_count = 0
fail_count = 0
all_averages = []
class_topper_name = ""
highest_avg = -1

#Print the Header and Loop
print(f"{'Name':<18} | {'Average':<8} | {'Status'}")
print("-" * 45) #Separating the labels from the data.

for name, marks in class_data:
    avg = round(sum(marks) / len(marks), 2)  # Compute average
    all_averages.append(avg)
    status = "Pass" if avg >= 60 else "Fail" # Assign status

    # Update pass/fail counters
    if status == "Pass":
        pass_count += 1
    else:
        fail_count += 1

    # Check for topper
    if avg > highest_avg:
        highest_avg = avg
        class_topper_name = name

    print(f"{name:<18} | {avg:<8.2f} | {status}")
print("-" * 45) #Print Final Summary
class_avg = round(sum(all_averages) / len(all_averages), 2)

print(f"Number of students who passed: {pass_count}")
print(f"Number of students who failed: {fail_count}")
print(f"Class topper: {class_topper_name} ({highest_avg})")
print(f"Class average: {class_avg}")

#Task 4
essay = "  python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning.  "
clean_essay=essay.strip() #strip whitespaces and store in clean_essay.
print(f"Step 1 (Clened essay):{clean_essay}")
print(f"Step 2 (Title case):{clean_essay.title()}")

python_count=clean_essay.count("python") #count "python".
print(f"Step 3 (Count of 'python'):{python_count}")

replaced_essay=clean_essay.replace("python","Python 🐍") #replacing python.
print(f"Step 4 (Replacement):{replaced_essay}")

sentences = [s.strip() for s in clean_essay.split(".") if s.strip()] #spit into individual sentences on ".".
print(f"Step 5 (Split List): {sentences}")

print("Step 6 (Numbered Sentences):") #printing numbered sentences with period check.
for i, sentence in enumerate(sentences, 1):
    if not sentence.endswith("."):
      sentence +="."
    print(f"{i}: {sentence}")